language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - git submodule update --init --recursive
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
after_success:
  - curl https://raw.githubusercontent.com/kmcallister/travis-doc-upload/master/travis-doc-upload.sh | sh
