language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.4.0
  - 1.3.0
  - 1.2.0
  - 1.1.0
  - 1.0.0
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
    - rust: 1.4.0
    - rust: 1.3.0
    - rust: 1.2.0
    - rust: 1.1.0
    - rust: 1.0.0
before_install:
  - git submodule update --init --recursive
script:
  - cargo build --features "clippy latest" --verbose
  - cargo test --features "clippy latest" --verbose
  - cargo doc --features "latest" --verbose
after_success:
  - ./scripts/travis-doc-upload.sh
