[package]
name = "rl-sys"
version = "0.2.1"
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
description = "Native bindings to libreadline."
documentation = "https://github.com/rustyhorde/readline-sys.git"
homepage = "https://github.com/rustyhorde/readline-sys.git"
repository = "https://github.com/rustyhorde/readline-sys.git"
keywords = ["readline", "readline-sys", "rl-sys"]
license = "MIT"
links = "readline"
build = "build.rs"

[dependencies]
libc = "~0.2.2"

[lib]
name = "rl_sys"
