[package]
name = "rl-sys"
version = "0.1.3-pre"
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
links = "readline"
build = "build.rs"
repository = "https://github.com/rustyhorde/readline-sys.git"
license = "MIT"
description = "Native bindings to the readline library"

[dependencies]
libc = "*"

[lib]
name = "rl_sys"
